### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by Gaming32**
+ Remove more biased options.txt values
+ Make the accessibility onboarding screen open properly
+ Remove World Host config from versions that don't have World Host
+ Add Borderless Mining
+ Replace FLK with QKL where possible
+ Remove Krypton

### CODE REVIEW

**Comment by Gaming32** [comment]
Also resolves #17 and #18.

**Review by intergrav — DISMISSED** [review]
While I agree with everything else, I'm curious about these two things:
- Remove more biased options.txt values
    - I'd like the simulation distance to be set to 5 as doing so *can* generally improve performance, but I do understand the other changes
- Remove Krypton
    - When it was temporarily removed from Adrenaline, we had a discussion about the removal in the Simply Optimized Discord server and HyperSoop had found that it can help with CPU usage in servers where there are a high amount of players, such as Hypixel. I can't confirm how true this is though (I personally don't see a difference but also have a pretty decent computer and internet speeds)

**Comment by Gaming32** [comment]
+ The sim distance could be kept ig
+ Krypton really doesn't do much on the client. If anything, ImmediatelyFast does *way* more for many entities. But I'm serious when I say Krypton basically does nothing at all (*on the client*). Krypton also has some major issues that the dev refuses to fix. For instance, try joining viaproxy.raphimc.net with Krypton, and then try without. You'll fail the antibot check with Krypton installed because Krypton violates certain specs of the Minecraft protocol.

**Comment by intergrav** [comment]
Oh now I see why. Do you have any other examples of Krypton breaking things? I'll likely remove it from Adrenaline either way as it hasn't been proven to do basically anything on the client and I understand the stuff you said before

**Comment by Gaming32** [comment]
I don't have any other specific examples, but I'm sure @RaphiMC could provide a few. As for the simulation-distance, that is technically changing behavior that a new player wouldn't necessarily understand. I feel like that kind of change belongs more in just Adrenaline, as that's all about performance, and is such targeted to weaker PCs.

**Comment by intergrav** [comment]
I see what you are saying. Well, this PR should be good then - I’ll merge it while I’m working on the next update so that the auto updating instance doesn’t get too out of sync with the Modrinth pack. Thanks :)

**Comment by RaphiMC** [comment]
While I don't have any more examples of Krypton violating the minecraft protocol, I can say that it does pretty much nothing on the client and is definitely not worth the network level changes (and mod incompatibilities) it makes.

**Pull request merged**
